### PR TITLE
Fix back button on demo home page

### LINKED ISSUE #28: Pressing 'back' on browser on the demo site redirects back to the catalog
From https://backstage.io/demos page when I click on the demo site, it redirects to demo.backstage.io which further redirects to `/catalog`. Now if the user wants to go back to the backstage.io page, pressing Back button doesn't help, since it's stuck in the redirect loop.

## Possible solution

The redirect from `/` to `/catalog` shouldn't override the browser history API, so that back button has access to the original site that referred to the demo site.

### PR DESCRIPTION
**Pull request by timbonicus**
Fixes #28

Adds `replace` to the `/` -> `/catalog` redirect so the back button works. I ran `App.test.tsx` and discovered it was out of date; updated from the `create-app` template.

### CODE REVIEW

File: packages/app/src/App.tsx [hunk 1]
```diff
@@ -43,7 +43,7 @@ const AppRouter = app.getRouter();
 
 const routes = (
   <FlatRoutes>
-    <Navigate key="/" to="/catalog" />
+    <Navigate key="/" to="/catalog" replace />
```
Comment (OrkoHunter) [inline packages/app/src/App.tsx:46]: ❤️

**Review by OrkoHunter — APPROVED** [review]
